version: "3.9"

services:
  ###########################
  #   server container
  ###########################
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn app.api.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # hostPath:containerPath:mode
      - ./server:/server:consistent
    ports:
      - "8000:8000"
